fix: correct HDI MidiDeviceInfo field names in midi_device_usb.cpp
Fix compile error in dayu200_tdd build:
- device.productName -> device.deviceName
- device.productName -> device.productId
- device.vendorName -> device.vendorId

The previous incorrect field names caused:
error: no member named 'deviceName' in 'OHOS::HDI::Midi::V1_0::MidiDeviceInfo'

Signed-off-by: owen_creeper <ouhanjun3@huawei.com>